# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Builds

on:
  # Push to any tracked branches
  push:
    branches: [master]
  # PRs only on master branch
  pull_request:
    branches: [master]
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for build'
        required: true

jobs:
  build:
    name: Ferdi Recipes Build
    runs-on: ubuntu-latest
    steps:
      - name: Print latest commit
        run: echo ${{ github.sha }}
      - name: Set env vars
        run: echo "PNPM_CACHE=$HOME/.pnpm-store" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js specified in the '.nvmrc' file
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.1
      - name: Install node dependencies recursively
        run: pnpm i && pnpm run package
